### ISSUE TITLE
[jdk21][upstream]java/nio/channels/DatagramChannel/AdaptorMulticasting.java用例-Xcomp选项概率性失败:message shouldn't have been received

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#103]
任务链接： https://tone.aliyun-inc.com/ws/xesljfzh/test_result/363906?tab=2

【环境准备】
```
jtreg=oss://compiler-ci-bucket/jdk/tools/jtreg-7.4.1.zip
BINARY_URL=oss://ajdk-backup/21.0.4.0.4-test-ajdk_ga/OpenJDK21U-jdk_aarch64_linux_ajdk_2024-09-02-03-26.tar.gz
TEST_IMAGE=oss://ajdk-backup/21.0.4.0.4-test-ajdk_ga/OpenJDK21U-testimage_aarch64_linux_ajdk_2024-09-02-03-26.tar.gz
JDK_REPO=https://codeup.aliyun.com/5f4e0dfe6207a1a8b17fa7cf/compiler-test/jdk21u.git
JDK_BRANCH=ajdk_ga-21.0.4.0.4


#下载解压jtreg，cd jtreg并配置
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
#下载解压jdk，cd <目录>并配置
export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME
#下载jdk-repo
git clone https://${JDK_REPO} --depth 1 -b $JDK_BRANCH jdk-repo

#执行测试
rm -rf tmp ; nproc=`nproc` ; dir="jt-work" ; rm -rf $dir ; mkdir -p $dir ; time seq 100 | xargs -i -n 1 -P  5 bash -c " \
 jtreg  -nr -v:fail,error -w tmp -timeoutFactor:4.0  -jdk:jdk-21.0.3.0.3+0   -Xcomp  java/nio/channels/DatagramChannel/AdaptorMulticasting.java \
 &> $dir/test_{}.log ; grep 'Test results: passed: 1' -L $dir/test_{}.log "

```   

```
#失败的case：
java/nio/channels/DatagramChannel/AdaptorMulticasting.java

```

【测试分析】

```
此用例目前在x86和aarch64上，是概率性失败： 失败概率30%
release 版本同样问题：
oss://ajdk-backup/21.0.3.0.3/OpenJDK21U-jdk_aarch64_linux_ajdk_2024-06-13-02-19.tar.gz 

release dragwell21 同样问题：
https://dragonwell.oss-cn-shanghai.aliyuncs.com/21.0.4.0.4%2B7/Alibaba_Dragonwell_Extended_21.0.4.0.4.7_aarch64_linux.tar.gz  

temurin 同样问题：
oss://compiler-ci-bucket/openjdk/jdk-21.0.4-ga/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.4_7.tar.gz 

```

【用例日志】

```
STDOUT:
Test family=INET, multicast group=/225.4.5.6, interface=eth0
testJoinGroup1: local socket address: /0.0.0.0:39547
testSendReceive
testSendNoReceive
testJoinGroup2: local socket address: /0.0.0.0:33874
testSendReceive
testSendNoReceive
testSendReceive
testSendNoReceive
Test family=UNSPEC, multicast group=/225.4.5.6, interface=eth0
testJoinGroup1: local socket address: /[0:0:0:0:0:0:0:0]:37464
testSendReceive
testSendNoReceive
testJoinGroup2: local socket address: /[0:0:0:0:0:0:0:0]:52317
testSendReceive
testSendNoReceive
testSendReceive
testSendNoReceive
Test family=INET6, multicast group=/225.4.5.6, interface=eth0
testJoinGroup1: local socket address: /[0:0:0:0:0:0:0:0]:44483
testSendReceive
testSendNoReceive
testJoinGroup2: local socket address: /[0:0:0:0:0:0:0:0]:36519
testSendReceive
testSendNoReceive
testSendReceive
testSendNoReceive
Test family=UNSPEC, multicast group=/ff02:0:0:0:0:0:0:a, interface=eth0
testJoinGroup1: local socket address: /[0:0:0:0:0:0:0:0]:57640
testSendReceive
testSendNoReceive
testJoinGroup2: local socket address: /[0:0:0:0:0:0:0:0]:45084
testSendReceive
testSendNoReceive
testSendReceive
testSendNoReceive
Test family=INET6, multicast group=/ff02:0:0:0:0:0:0:a, interface=eth0
testJoinGroup1: local socket address: /[0:0:0:0:0:0:0:0]:45282
testSendReceive
testSendNoReceive
STDERR:
java.lang.RuntimeException: message shouldn't have been received
	at AdaptorMulticasting.testSendNoReceive(AdaptorMulticasting.java:459)
	at AdaptorMulticasting.testJoinGroup1(AdaptorMulticasting.java:160)
	at AdaptorMulticasting.test(AdaptorMulticasting.java:93)
	at AdaptorMulticasting.main(AdaptorMulticasting.java:81)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1616)

JavaTest Message: Test threw exception: java.lang.RuntimeException: message shouldn't have been received
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: message shouldn't have been received


```

【版本信息】   
#测试机及其jdk环境信息   
```
#uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;./java -version; ./java -Xinternalversion
Linux CompilerTest-aarch64-2 5.10.134-16.1.al8.aarch64 #1 SMP Thu Dec 7 22:04:51 CST 2023 aarch64 aarch64 aarch64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          122Gi       1.4Gi        38Gi       0.0Ki        82Gi       119Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        1
Vendor ID:           ARM
Model:               0
Model name:          Neoverse-N2
Stepping:            r0p0
CPU MHz:             3000.000
CPU max MHz:         3000.0000
CPU min MHz:         3000.0000
BogoMIPS:            100.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
L3 cache:            65536K
NUMA node0 CPU(s):   0-31
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs sb dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint svei8mm svebf16 i8mm bf16 dgh
openjdk version "21.0.3.0.3-AJDK" 2024-09-02
OpenJDK Runtime Environment (Alibaba AJDK) (build 21.0.3.0.3-AJDK+21-Alibaba)
OpenJDK 64-Bit Server VM (Alibaba AJDK) (build 21.0.3.0.3-AJDK+21-Alibaba, mixed mode, sharing)
OpenJDK 64-Bit Server VM (21.0.3.0.3-AJDK+21-Alibaba) for linux-aarch64 JRE (21.0.3.0.3-AJDK+21-Alibaba), built on 2024-09-02T03:29:48Z by "root" with gcc 11.2.0


```

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/18201509

**Comment by sendaoYan** [comment]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/364581

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8247669
