### ISSUE TITLE
[nightly]com/sun/jdi/EATests.java报错VM option 'LockingMode' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#118]
任务链接：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/393285?tab=3

【环境准备】
```
BINARY_URL=oss://compiler-ci-bucket/dragonwell21/20241026-001817-667-#238-linux.x86_64.release.master-e8044f61a08dd6e973a36e220f0143afc05aea29.jdk.tar.gz
TEST_IMAGE=oss://compiler-ci-bucket/dragonwell21/20241026-001817-667-#238-linux.x86_64.release.master-e8044f61a08dd6e973a36e220f0143afc05aea29.test-image.tar.gz
JDK_REPO=git@github.com:dragonwell-project/dragonwell21.git
JDK_BRANCH=master



jtreg=oss://compiler-ci-bucket/jdk/tools/jtreg-7.4.1.zip

#下载解压jtreg，cd jtreg并配置
export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH
#下载解压jdk，cd <目录>并配置
export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME
#下载jdk-repo
git clone https://${JDK_REPO} --depth 1 -b $JDK_BRANCH jdk-repo

#执行测试
jtreg -w tmp -nr -v:fail,error  com/sun/jdi/EATests.java


```   

【测试分析】

```   
com/sun/jdi/EATests.java#id0

x86-64、arm上都存在。

release版本/上游都存在。

```

【版本信息】     

#jdk信息   
```
[root@CompilerTest-x64-5 new]# bin/java -version; bin/java -Xinternalversion
openjdk version "21.0.4.0.4" 2024-10-26
OpenJDK Runtime Environment (build 21.0.4.0.4+21)
OpenJDK 64-Bit Server VM (build 21.0.4.0.4+21, mixed mode, sharing)
OpenJDK 64-Bit Server VM (21.0.4.0.4+21) for linux-amd64 JRE (21.0.4.0.4+21), built on 2024-10-25T16:19:58Z by "admin" with gcc 11.2.0


 
```    

#测试机信息jdk环境信息     
```
[root@CompilerTest-x64-5 ~]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25; dmidecode -t chassis
Linux CompilerTest-x64-5 5.10.134-16.1.al8.x86_64 #1 SMP Thu Dec 7 14:11:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          123Gi       711Mi       116Gi       2.0Mi       5.9Gi       121Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Alibaba Cloud
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
BIOS Model name:     pc-i440fx-2.1
Stepping:            6
CPU MHz:             3502.594
BogoMIPS:            5399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-31
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x0300, DMI type 3, 21 bytes
Chassis Information
        Manufacturer: Alibaba Cloud
        Type: Other
        Lock: Not Present
        Version: pc-i440fx-2.1
        Serial Number: Not Specified
        Asset Tag: Not Specified
        Boot-up State: Safe
        Power Supply State: Safe
        Thermal State: Safe
        Security Status: Unknown
        OEM Information: 0x00000000
        Height: Unspecified
        Number Of Power Cords: Unspecified
        Contained Elements: 0




```

【用例日志】
```
ACTION: driver -- Failed. Execution failed: `main' threw exception: java.lang.NullPointerException: Cannot invoke "com.sun.jdi.VirtualMachine.setDebugTraceMode(int)" because "this.vm" is null
REASON: User specified action: run driver EATests -XX:+UnlockDiagnosticVMOptions -Xms256m -Xmx256m -Xbootclasspath/a:. -XX:CompileCommand=dontinline,*::dontinline_* -XX:+WhiteBoxAPI -Xbatch -XX:+DoEscapeAnalysis -XX:+EliminateAllocations -XX:+EliminateLocks -XX:+EliminateNestedLocks -XX:LockingMode=1 -XX:DiagnoseSyncOnValueBasedClasses=2 
TIME:   0.177 seconds
messages:
command: driver EATests -XX:+UnlockDiagnosticVMOptions -Xms256m -Xmx256m -Xbootclasspath/a:. -XX:CompileCommand=dontinline,*::dontinline_* -XX:+WhiteBoxAPI -Xbatch -XX:+DoEscapeAnalysis -XX:+EliminateAllocations -XX:+EliminateLocks -XX:+EliminateNestedLocks -XX:LockingMode=1 -XX:DiagnoseSyncOnValueBasedClasses=2
reason: User specified action: run driver EATests -XX:+UnlockDiagnosticVMOptions -Xms256m -Xmx256m -Xbootclasspath/a:. -XX:CompileCommand=dontinline,*::dontinline_* -XX:+WhiteBoxAPI -Xbatch -XX:+DoEscapeAnalysis -XX:+EliminateAllocations -XX:+EliminateLocks -XX:+EliminateNestedLocks -XX:LockingMode=1 -XX:DiagnoseSyncOnValueBasedClasses=2 
started: Mon Oct 28 00:48:42 CST 2024
Mode: othervm
Additional options from @modules: --add-modules jdk.jdi
finished: Mon Oct 28 00:48:42 CST 2024
elapsed time (seconds): 0.177
configuration:
Boot Layer
  add modules: jdk.jdi

STDOUT:

###(Debugger) starting to main method in class EATestsTarget

vmOpts: '-Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -ea -esa'
javaOpts: ''
Error: VM option 'LockingMode' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.
Error: The unlock option must precede 'LockingMode'.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
STDERR:
[2ms] run args: [-XX:+UnlockDiagnosticVMOptions, -Xms256m, -Xmx256m, -Xbootclasspath/a:., -XX:CompileCommand=dontinline,*::dontinline_*, -XX:+WhiteBoxAPI, -Xbatch, -XX:+DoEscapeAnalysis, -XX:+EliminateAllocations, -XX:+EliminateLocks, -XX:+EliminateNestedLocks, -XX:LockingMode=1, -XX:DiagnoseSyncOnValueBasedClasses=2, EATestsTarget]
VM initialization failed for: /tmp/tone/run/jtreg/binary-download/bin/java -classpath /tmp/tone/run/jtreg/jt-work/jtreg/test_jdk/classes/94/com/sun/jdi/EATests_id0.d:/tmp/tone/run/jtreg/jt-work/jtreg/test_jdk/classes/94/test/lib:/tmp/tone/run/jtreg/jt-work/jtreg/test_jdk/classes/94/test/hotspot/jtreg -Djdk.lang.processReaperUseDefaultStackSize=true -Dtest.wisp.socketAddress=www.alibabacloud.com -ea -esa -XX:+UnlockDiagnosticVMOptions -Xms256m -Xmx256m -Xbootclasspath/a:. -XX:CompileCommand=dontinline,*::dontinline_* -XX:+WhiteBoxAPI -Xbatch -XX:+DoEscapeAnalysis -XX:+EliminateAllocations -XX:+EliminateLocks -XX:+EliminateNestedLocks -XX:LockingMode=1 -XX:DiagnoseSyncOnValueBasedClasses=2 -Xdebug -Xrunjdwp:transport=dt_socket,address=localhost:40619,suspend=y,includevirtualthreads=y EATestsTarget


 Target VM failed to initialize.
java.lang.NullPointerException: Cannot invoke "com.sun.jdi.VirtualMachine.setDebugTraceMode(int)" because "this.vm" is null
	at VMConnection.open(VMConnection.java:160)
	at TestScaffold.connect(TestScaffold.java:709)
	at TestScaffold.startUp(TestScaffold.java:401)
	at TestScaffold.startTo(TestScaffold.java:411)
	at TestScaffold.startToMain(TestScaffold.java:406)
	at EATests.runTests(EATests.java:384)
	at TestScaffold.startTests(TestScaffold.java:468)
	at EATests.main(EATests.java:349)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1583)

JavaTest Message: Test threw exception: java.lang.NullPointerException: Cannot invoke "com.sun.jdi.VirtualMachine.setDebugTraceMode(int)" because "this.vm" is null
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.NullPointerException: Cannot invoke "com.sun.jdi.VirtualMachine.setDebugTraceMode(int)" because "this.vm" is null



```

**Comment by sendaoYan** [comment]
应该已经没有问题了

**Comment by sendaoYan** [comment]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/397794?tab=2
