### ISSUE TITLE
[21.0.5.0.5+9]-XX:+UseCompactObjectHeaders选项runtime/cds/BootAppendTests.java等214个CDS相关用例必现报错Hotspot crashed

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#126]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/394873?tab=1  
【环境准备】

```
BINARY_URL=oss://dragonwell/21.0.5.0.5+9-test-dragonwell_extended/Alibaba_Dragonwell_Extended_21.0.5.0.5.9_x64_linux.tar.gz
TEST_IMAGE=oss://dragonwell/21.0.5.0.5+9-test-dragonwell_extended/Alibaba_Dragonwell_Extended_21.0.5.0.5.9_x64_linux-testimage.tar.gz
JTREG_URL=oss://compiler-ci-bucket/jdk/tools/jtreg-7.3.1.1.zip
JDK_REPO=git@github.com:dragonwell-project/dragonwell21.git
JDK_BRANCH=dragonwell_extended-21.0.5.0.5+9
cd ~/tone/tone-matrix-compiler/common;./ossutil.bin_$(arch) -i;cd -
alias oss="~/tone/tone-matrix-compiler/common/ossutil.bin_$(arch) -e oss-cn-hangzhou.aliyuncs.com -u jvm_dev-b  ~/tone/tone-matrix-compiler/common/ossutil_bin/ossutil -o download -f -r"

部署二进制：
oss $BINARY_URL -l ${BINARY_URL##*/}
mkdir bin-dragonwell21;tar -xf ${BINARY_URL##*/} -C bin-dragonwell21
oss $TEST_IMAGE-l ${TEST_IMAGE##*/}
mkdir images-dragonwell21;tar -xf ${BINARY_URL##*/} -C images-dragonwell21

部署jtreg工具：
oss $JTREG_URL -l ${JTREG_URL##*/};unzip ${JTREG_URL##*/}

部署用例repo
git clone -b $JDK_BRANCH $JDK_REPO jdk-repo-dragonwell21

执行以下命令：
cd  bin-dragonwell21/dragonwell-21.0.4.0.4+7-GA/ && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
cd jtreg ;export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH;cd -

jtreg  -nr -v:fail,error -w tmp  -XX:+UseCompactObjectHeaders  jdk-repo-dragonwell21/test/hotspot/jtreg/runtime/cds/BootAppendTests.java
```  
【测试分析】    
x64,aarch64，都有问题，涉及用例214个，以下只列举部分   

```
runtime/cds/BootAppendTests.java
runtime/cds/CdsSameObjectAlignment.java
runtime/cds/DumpSharedDictionary.java
runtime/cds/PrimitiveClassMirrors.java
runtime/cds/ServiceLoaderTest.java
runtime/cds/SharedArchiveFile.java
runtime/cds/SharedBaseAddress.java#id0
runtime/cds/SharedBaseAddress.java#id1
runtime/cds/SharedBaseAddress.java#id2
runtime/cds/SharedBaseAddress.java#id3
runtime/cds/SharedStringsDedup.java
runtime/cds/SharedStringsRunAuto.java
runtime/cds/TestInterpreterMethodEntries.java#id0
runtime/cds/TestInterpreterMethodEntries.java#id1
runtime/cds/appcds/AppendClasspath.java
runtime/cds/appcds/ArchiveRelocationTest.java
runtime/cds/appcds/BootClassPathMismatch.java
runtime/cds/appcds/CDSandJFR.java
runtime/cds/appcds/ClassLoaderTest.java
runtime/cds/appcds/ClassPathAttr.java
runtime/cds/appcds/CommandLineFlagCombo.java
runtime/cds/appcds/CommonAppClasspath.java
runtime/cds/appcds/DuplicateClassPaths.java
runtime/cds/appcds/ExtraSymbols.java
runtime/cds/appcds/FieldAnnotationsTest.java
runtime/cds/appcds/FieldLayoutFlags.java
runtime/cds/appcds/FreeUnusedMetadata.java
runtime/cds/appcds/HelloExtTest.java
runtime/cds/appcds/HelloTest.java
runtime/cds/appcds/IgnoreEmptyClassPaths.java
runtime/cds/appcds/JvmtiAddPath.java
runtime/cds/appcds/LambdaContainsOldInf.java
runtime/cds/appcds/LambdaEagerInit.java
runtime/cds/appcds/LambdaWithOldClass.java
runtime/cds/appcds/LambdaWithUseImplMethodHandle.java
runtime/cds/appcds/MismatchedPathTriggerMemoryRelease.java
runtime/cds/appcds/MissingSuperTest.java
runtime/cds/appcds/MultiProcessSharing.java
```

【对比测试】  
dragonwell21 release 没有问题  
oss://dragonwell/21.0.4.0.4+7/Alibaba_Dragonwell_Extended_21.0.4.0.4.7_x64_linux.tar.gz  

Temurin21 不涉及  
【用例日志】

```
STDERR:
java.lang.RuntimeException: Hotspot crashed
        at jdk.test.lib.cds.CDSTestUtils.executeAndLog(CDSTestUtils.java:699)
        at jdk.test.lib.cds.CDSTestUtils.executeAndLog(CDSTestUtils.java:675)
        at jdk.test.lib.cds.CDSTestUtils.runWithArchive(CDSTestUtils.java:448)
        at BootAppendTests.testBootAppendModuleClass(BootAppendTests.java:142)
        at BootAppendTests.main(BootAppendTests.java:75)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
        at java.base/java.lang.Thread.run(Thread.java:1583)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Hotspot crashed
JavaTest Message: shutting down test
```
【jdk信息】

```
java -version;java -Xinternalversion
openjdk version "21.0.4.0.4" 2024-10-15
OpenJDK Runtime Environment (Alibaba Dragonwell Extended Edition)-21.0.4.0.4+7-GA (build 21.0.4.0.4)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Extended Edition)-21.0.4.0.4+7-GA (build 21.0.4.0.4, mixed mode, sharing)
OpenJDK 64-Bit Server VM (21.0.4.0.4) for linux-amd64 JRE (21.0.4.0.4), built on 2024-10-15T00:00:00Z by "dragonwell" with gcc 11.2.0
```

【系统版本信息】

```
uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25
Linux CompilerTest-x64-3 5.10.134-16.1.al8.x86_64 #1 SMP Thu Dec 7 14:11:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          123Gi       1.0Gi       113Gi       2.0Mi       9.3Gi       121Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
Stepping:            6
CPU MHz:             3518.487
BogoMIPS:            5399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities

```

**Comment by linade** [comment]
#124 fixing in progress

**Comment by linade** [comment]
Fixed, please confirm

**Comment by sendaoYan** [comment]
验证通过
