### ISSUE TITLE
[RISC-V]StreamFlowControlTest.java intermittent fails should sleep time be raised?

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#130]
job:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/402865?tab=1

```
Sending request:https://127.0.0.1:48057/https2/x?reqId=4
Server localhost/127.0.0.1:48057 received:
https://127.0.0.1:48057/https2/x?reqId=4: Hello there!
Server: response sent for reqId=4
test StreamFlowControlTest.test("https://127.0.0.1:48057/https2/x", false): failure
java.lang.AssertionError: Expected exception, got :(POST https://127.0.0.1:48057/https2/x?reqId=4) 200, should sleep time be raised?
	at org.testng.Assert.fail(Assert.java:99)
	at StreamFlowControlTest.test(StreamFlowControlTest.java:139)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
```

[StreamFlowControlTest.java.log](https://github.com/user-attachments/files/17728226/StreamFlowControlTest.java.log)

**Comment by sendaoYan** [comment]
rerun job:https://tone.aliyun-inc.com/ws/xesljfzh/test_result/403350?tab=3
fail probability: 129/1k
