### ISSUE TITLE
[ASAN][upstream][25][clang]compressedKlass.cpp:99:38: runtime error: applying non-zero offset 4294967296 to null pointer

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#143]
Configure command:
```
bash configure --with-jobs=128 --prefix=/home/yansendao/git/jdk-asan-clang/install-fastdebug --verbose --with-debug-level=fastdebug --enable-unlimited-crypto --with-vendor-name=yansendao --with-vendor-url=https://github.com/sendaoYan --with-vendor-bug-url=mailto:yansendao.ysd@alibaba-inc.com --with-vendor-vm-bug-url=mailto:yansendao.ysd@alibaba-inc.com --with-jvm-variants=server --with-boot-jdk=/home/yansendao/software/jdk/24/jdk-repo-binary --with-gtest=/home/yansendao/git/googletest-v1.14.x --with-jtreg=/home/yansendao/software/jdk/jtreg-7.4 --with-jmh=build/jmh/jars    --with-version-opt=23d6f747 --with-zlib=system --enable-ccache --with-native-debug-symbols=external --with-extra-cflags=-shared-libasan --with-extra-cxxflags=-shared-libasan --with-extra-ldflags=-shared-libasan  --enable-asan --enable-ubsan --enable-lsan --with-toolchain-type=clang --with-toolchain-path=~/software/acc/x86_64/bin
```

Standalone command:
```shell
/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/jdk/bin/javac -J-Djava.io.tmpdir=/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/support/javatmp -g -Xlint:all -source 25 -target 25 -implicit:none -Xprefer:source -XDignore.symbol.file=true -encoding ascii -Werror --add-modules jdk.compiler,jdk.jdeps --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED --add-exports jdk.jdeps/com.sun.tools.classfile=ALL-UNNAMED -Xlint:-options -XDmodifiedInputs=/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.modfiles.fixed -d /home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac @/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.filelist
```

result:
```
src/hotspot/share/oops/compressedKlass.cpp:99:38: runtime error: applying non-zero offset 4294967296 to null pointer
    #0 0x7f63ea790a9b in CompressedKlassPointers::sanity_check_after_initialization() /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/compressedKlass.cpp:99:38
    #1 0x7f63ea793023 in CompressedKlassPointers::initialize(unsigned char*, unsigned long) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/compressedKlass.cpp:292:3
    #2 0x7f63ec8d96fc in Metaspace::global_initialize() /home/yansendao/git/jdk-asan-clang/src/hotspot/share/memory/metaspace.cpp:808:5
    #3 0x7f63edd440d3 in universe_init() /home/yansendao/git/jdk-asan-clang/src/hotspot/share/memory/universe.cpp:888:3
    #4 0x7f63eb7e9213 in init_globals() /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/init.cpp:133:17
    #5 0x7f63edca80aa in Threads::create_vm(JavaVMInitArgs*, bool*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:574:17
    #6 0x7f63ebcbcbbe in JNI_CreateJavaVM_inner(JavaVM_**, void**, void*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3589:12
    #7 0x7f63ebcbcbbe in JNI_CreateJavaVM /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3680:14
    #8 0x7f63f33d59d1 in InitializeJVM /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:1495:9
    #9 0x7f63f33d59d1 in JavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:494:10
    #10 0x7f63f33e2910 in ThreadJavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/unix/native/libjli/java_md.c:649:29
    #11 0x7f63f3536a0a  (/home/yansendao/software/acc/x86_64/lib64/clang/17/lib/linux/libclang_rt.asan-x86_64.so+0x136a0a)
    #12 0x7f63f33763fa in start_thread pthread_create.c
    #13 0x7f63f31cce82 in clone (/lib64/libc.so.6+0x3de82) (BuildId: 3308b7b1df603240fd3f43dd895bcb2ad87e7eb9)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/hotspot/share/oops/compressedKlass.cpp:99:38 in 
```

Well known issue suppress:
```shell
export UBSAN_OPTIONS="suppressions=$HOME/tone/tone-matrix-compiler/jtreg/asan/suppressions-UndefinedBehavior-clang.txt"
```
```log
#https://github.com/dragonwell-project/dragonwell21/issues/142
function:InitializeJVM
```

[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18205345/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18205347/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18205348/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk/pull/22848
