### ISSUE TITLE
[ASAN][upstream][25][clang]ni_util.c:733:9: runtime error: call to function jni_EnsureLocalCapacity through pointer to incorrect function type 'int (*)(const struct JNINativeInterface_ **, int)'

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#151]
Configure command:
```
export PATH=~/software/acc/`arch`/bin:$PATH ; export LD_LIBRARY_PATH=~/software/acc/`arch`/lib64/clang/17/lib/linux:$LD_LIBRARY_PATH ; export CFLAGS="-shared-libasan" ; export CXXFLAGS=$CFLAGS ; export LDFLAGS=$CFLAGS ; export "CUSTOM_CONFIG=--enable-asan --enable-ubsan --enable-lsan --with-toolchain-type=clang --with-toolchain-path=~/software/acc/`arch`/bin" && export ASAN_OPTIONS="detect_leaks=0,abort_on_error=0,verbosity=3" && export LSAN_OPTIONS=suppressions=$HOME/tone/tone-matrix-compiler/jtreg/asan/leak-suppressions.txt && export UBSAN_OPTIONS="suppressions=$HOME/tone/tone-matrix-compiler/jtreg/asan/suppressions-UndefinedBehavior-clang.txt,print_stacktrace=1"
bash configure --with-jobs=128 --prefix=/home/yansendao/git/jdk-asan-clang/install-fastdebug --verbose --with-debug-level=fastdebug --enable-unlimited-crypto --with-vendor-name=yansendao --with-vendor-url=https://github.com/sendaoYan --with-vendor-bug-url=mailto:yansendao.ysd@alibaba-inc.com --with-vendor-vm-bug-url=mailto:yansendao.ysd@alibaba-inc.com --with-jvm-variants=server --with-boot-jdk=/home/yansendao/software/jdk/24/jdk-repo-binary --with-gtest=/home/yansendao/git/googletest-v1.14.x --with-jtreg=/home/yansendao/software/jdk/jtreg-7.4 --with-jmh=build/jmh/jars    --with-version-opt=23d6f747 --with-zlib=system --enable-ccache --with-native-debug-symbols=external --with-extra-cflags=-shared-libasan --with-extra-cxxflags=-shared-libasan --with-extra-ldflags=-shared-libasan  --enable-asan --enable-ubsan --enable-lsan --with-toolchain-type=clang --with-toolchain-path=~/software/acc/x86_64/bin
```

Standalone command:
```shell
/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/jdk/bin/javac -J-Djava.io.tmpdir=/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/support/javatmp -g -Xlint:all -source 25 -target 25 -implicit:none -Xprefer:source -XDignore.symbol.file=true -encoding ascii -Werror --add-modules jdk.compiler,jdk.jdeps --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED --add-exports jdk.jdeps/com.sun.tools.classfile=ALL-UNNAMED -Xlint:-options -XDmodifiedInputs=/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.modfiles.fixed -d /home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac @/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.filelist
```

result:
```
src/java.base/share/native/libjava/jni_util.c:733:9: runtime error: call to function jni_EnsureLocalCapacity through pointer to incorrect function type 'int (*)(const struct JNINativeInterface_ **, int)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:718: note: jni_EnsureLocalCapacity defined here
    #0 0x7fbd159a0251 in InitializeEncoding /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/jni_util.c:733:9
    #1 0x7fbd1598c6e5 in Java_jdk_internal_util_SystemProps_00024Raw_platformProperties /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/System.c:121:5
    #2 0x7fbd01495d44  (<unknown module>)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/jni_util.c:733:9 in
```

[configure-command.txt](https://github.com/user-attachments/files/18244018/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18244019/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18244020/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18244021/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18244022/make-linux-x86_64-server-fastdebug-1.log.zip)

**Comment by sendaoYan** [comment]
```
src/java.base/share/native/libjava/jni_util.c:994:13: runtime error: call to function jni_EnsureLocalCapacity through pointer to incorrect function type 'int (*)(const struct JNINativeInterface_ **, int)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:718: note: jni_EnsureLocalCapacity defined here
    #0 0x7ffb863d561c in JNU_ClassString /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/jni_util.c:994:13
    #1 0x7ffb863d4b8c in InitializeEncoding /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/jni_util.c:736:16
    #2 0x7ffb863c16e5 in Java_jdk_internal_util_SystemProps_00024Raw_platformProperties /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/System.c:121:5
    #3 0x7ffb71e95d44  (<unknown module>)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/jni_util.c:994:13 in
```

[configure-command.txt](https://github.com/user-attachments/files/18244100/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18244101/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18244102/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18244104/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18244105/make-linux-x86_64-server-fastdebug-1.log.zip)

**Comment by sendaoYan** [comment]
```
src/java.base/share/native/libjava/jni_util.c:220:9: runtime error: call to function jni_EnsureLocalCapacity through pointer to incorrect function type 'int (*)(const struct JNINativeInterface_ **, int)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:718: note: jni_EnsureLocalCapacity defined here
    #0 0x7f100c29eb15 in JNU_CallStaticMethodByName /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/jni_util.c:220:9
    #1 0x7f100c29ff3b in InitializeEncoding /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/jni_util.c:778:30
    #2 0x7f100c28c6e5 in Java_jdk_internal_util_SystemProps_00024Raw_platformProperties /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/System.c:121:5
    #3 0x7f0ff7d95d44  (<unknown module>)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/jni_util.c:220:9 in
```

[configure-command.txt](https://github.com/user-attachments/files/18244116/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18244117/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18244118/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18244119/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18244120/make-linux-x86_64-server-fastdebug-1.log.zip)

**Comment by sendaoYan** [comment]
```
src/java.base/share/native/libjava/System.c:124:9: runtime error: call to function jni_EnsureLocalCapacity through pointer to incorrect function type 'int (*)(const struct JNINativeInterface_ **, int)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:718: note: jni_EnsureLocalCapacity defined here
    #0 0x7f06c165965a in Java_jdk_internal_util_SystemProps_00024Raw_platformProperties /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/System.c:124:9
    #1 0x7f06ad195d44  (<unknown module>)
    #2 0x7f06ad18f1ed  (<unknown module>)
    #3 0x7f06ad18f415  (<unknown module>)
    #4 0x7f06ad18f1ed  (<unknown module>)
    #5 0x7f06ad187d00  (<unknown module>)
    #6 0x7f06bc71689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #7 0x7f06bc7127b8 in JavaCalls::call(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:324:3
    #8 0x7f06bc7127b8 in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:251:3
    #9 0x7f06bc712cda in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:257:3
    #10 0x7f06beaab6cb in call_initPhase1(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:298:3
    #11 0x7f06beaa8a6d in Threads::initialize_java_lang_classes(JavaThread*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:382:3
    #12 0x7f06beaad310 in Threads::create_vm(JavaVMInitArgs*, bool*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:669:3
    #13 0x7f06bcac135e in JNI_CreateJavaVM_inner(JavaVM_**, void**, void*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3589:12
    #14 0x7f06bcac135e in JNI_CreateJavaVM /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3680:14
    #15 0x7f06c43d59d1 in InitializeJVM /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:1495:9
    #16 0x7f06c43d59d1 in JavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:494:10
    #17 0x7f06c43e2910 in ThreadJavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/unix/native/libjli/java_md.c:649:29
    #18 0x7f06c4536a0a  (/home/yansendao/software/acc/x86_64/lib64/clang/17/lib/linux/libclang_rt.asan-x86_64.so+0x136a0a)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/System.c:124:9 in
```
[configure-command.txt](https://github.com/user-attachments/files/18244177/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18244178/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18244179/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18244180/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18244181/make-linux-x86_64-server-fastdebug-1.log.zip)

**Comment by sendaoYan** [comment]
```
src/java.base/share/native/libjava/jni_util.c:408:9: runtime error: call to function jni_EnsureLocalCapacity through pointer to incorrect function type 'int (*)(const struct JNINativeInterface_ **, int)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:718: note: jni_EnsureLocalCapacity defined here
    #0 0x7fc230da75cd in newSizedString8859_1 /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/jni_util.c:408:9
    #1 0x7fc230da0afa in newStringUTF8 /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/jni_util.c:719:16
    #2 0x7fc230da0afa in JNU_NewStringPlatform /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/jni_util.c:823:16
    #3 0x7fc230d8e2a0 in Java_jdk_internal_util_SystemProps_00024Raw_platformProperties /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/System.c:215:5
    #4 0x7fc21c895d44  (<unknown module>)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/jni_util.c:408:9 in
```
[configure-command.txt](https://github.com/user-attachments/files/18244367/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18244368/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18244369/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18244371/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18244372/make-linux-x86_64-server-fastdebug-1.log.zip)
