### ISSUE TITLE
[ASAN][upstream][25][clang]FileInputStream.c:52:14: runtime error: call to function jni_GetFieldID through pointer to incorrect function type 'struct _jfieldID *(*)(const struct JNINativeInterface_ **, struct _jobject *, const char *, const char *)'

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#154]
Configure command:
```
export PATH=~/software/acc/`arch`/bin:$PATH ; export LD_LIBRARY_PATH=~/software/acc/`arch`/lib64/clang/17/lib/linux:$LD_LIBRARY_PATH ; export CFLAGS="-shared-libasan" ; export CXXFLAGS=$CFLAGS ; export LDFLAGS=$CFLAGS ; export "CUSTOM_CONFIG=--enable-asan --enable-ubsan --enable-lsan --with-toolchain-type=clang --with-toolchain-path=~/software/acc/`arch`/bin" && export ASAN_OPTIONS="detect_leaks=0,abort_on_error=0,verbosity=3" && export LSAN_OPTIONS=suppressions=$HOME/tone/tone-matrix-compiler/jtreg/asan/leak-suppressions.txt && export UBSAN_OPTIONS="suppressions=$HOME/tone/tone-matrix-compiler/jtreg/asan/suppressions-UndefinedBehavior-clang.txt,print_stacktrace=1"
bash configure --with-jobs=128 --prefix=/home/yansendao/git/jdk-asan-clang/install-fastdebug --verbose --with-debug-level=fastdebug --enable-unlimited-crypto --with-vendor-name=yansendao --with-vendor-url=https://github.com/sendaoYan --with-vendor-bug-url=mailto:yansendao.ysd@alibaba-inc.com --with-vendor-vm-bug-url=mailto:yansendao.ysd@alibaba-inc.com --with-jvm-variants=server --with-boot-jdk=/home/yansendao/software/jdk/24/jdk-repo-binary --with-gtest=/home/yansendao/git/googletest-v1.14.x --with-jtreg=/home/yansendao/software/jdk/jtreg-7.4 --with-jmh=build/jmh/jars    --with-version-opt=23d6f747 --with-zlib=system --enable-ccache --with-native-debug-symbols=external --with-extra-cflags=-shared-libasan --with-extra-cxxflags=-shared-libasan --with-extra-ldflags=-shared-libasan  --enable-asan --enable-ubsan --enable-lsan --with-toolchain-type=clang --with-toolchain-path=~/software/acc/x86_64/bin
```

Standalone command:
```shell
/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/jdk/bin/javac -J-Djava.io.tmpdir=/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/support/javatmp -g -Xlint:all -source 25 -target 25 -implicit:none -Xprefer:source -XDignore.symbol.file=true -encoding ascii -Werror --add-modules jdk.compiler,jdk.jdeps --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED --add-exports jdk.jdeps/com.sun.tools.classfile=ALL-UNNAMED -Xlint:-options -XDmodifiedInputs=/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.modfiles.fixed -d /home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac @/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.filelist
```

result:
```
src/java.base/share/native/libjava/FileInputStream.c:52:14: runtime error: call to function jni_GetFieldID through pointer to incorrect function type 'struct _jfieldID *(*)(const struct JNINativeInterface_ **, struct _jobject *, const char *, const char *)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:1747: note: jni_GetFieldID defined here
    #0 0x7fdfb93b5333 in Java_java_io_FileInputStream_initIDs /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/FileInputStream.c:52:14
    #1 0x7fdfa4e95d44  (<unknown module>)
    #2 0x7fdfa4e8f415  (<unknown module>)
    #3 0x7fdfa4e87d00  (<unknown module>)
    #4 0x7fdfb431689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #5 0x7fdfb4204c18 in InstanceKlass::call_class_initializer(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:1704:5
    #6 0x7fdfb41fb02a in InstanceKlass::initialize_impl(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:1313:7
    #7 0x7fdfb41f8777 in InstanceKlass::initialize(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:816:5
    #8 0x7fdfb41f9f44 in InstanceKlass::initialize_impl(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:1274:20
    #9 0x7fdfb41f8777 in InstanceKlass::initialize(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:816:5
    #10 0x7fdfb42acf80 in InterpreterRuntime::_new(JavaThread*, ConstantPool*, int) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/interpreter/interpreterRuntime.cpp:221:10
    #11 0x7fdfa4ea9c7b  (<unknown module>)
    #12 0x7fdfa4e87d00  (<unknown module>)
    #13 0x7fdfb431689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #14 0x7fdfb43127b8 in JavaCalls::call(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:324:3
    #15 0x7fdfb43127b8 in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:251:3
    #16 0x7fdfb4312cda in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:257:3
    #17 0x7fdfb66ab6cb in call_initPhase1(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:298:3
    #18 0x7fdfb66a8a6d in Threads::initialize_java_lang_classes(JavaThread*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:382:3
    #19 0x7fdfb66ad310 in Threads::create_vm(JavaVMInitArgs*, bool*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:669:3
    #20 0x7fdfb46c135e in JNI_CreateJavaVM_inner(JavaVM_**, void**, void*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3589:12
    #21 0x7fdfb46c135e in JNI_CreateJavaVM /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3680:14
    #22 0x7fdfbcc999d1 in InitializeJVM /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:1495:9
    #23 0x7fdfbcc999d1 in JavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:494:10
    #24 0x7fdfbcca6910 in ThreadJavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/unix/native/libjli/java_md.c:649:29
    #25 0x7fdfbc136a0a  (/home/yansendao/software/acc/x86_64/lib64/clang/17/lib/linux/libclang_rt.asan-x86_64.so+0x136a0a)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/FileInputStream.c:52:14 in
```

**Comment by sendaoYan** [comment]
```
src/java.base/unix/native/libjava/FileDescriptor_md.c:52:5: runtime error: call to function jni_GetFieldID through pointer to incorrect function type 'struct _jfieldID *(*)(const struct JNINativeInterface_ **, struct _jobject *, const char *, const char *)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:1747: note: jni_GetFieldID defined here
    #0 0x7f83837be06b in Java_java_io_FileDescriptor_initIDs /home/yansendao/git/jdk-asan-clang/src/java.base/unix/native/libjava/FileDescriptor_md.c:52:5
    #1 0x7f836f495d44  (<unknown module>)
    #2 0x7f836f48f415  (<unknown module>)
    #3 0x7f836f487d00  (<unknown module>)
    #4 0x7f837e91689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #5 0x7f837e804c18 in InstanceKlass::call_class_initializer(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:1704:5
    #6 0x7f837e7fb02a in InstanceKlass::initialize_impl(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:1313:7
    #7 0x7f837e7f8777 in InstanceKlass::initialize(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:816:5
    #8 0x7f837f4aeaa6 in LinkResolver::resolve_field(fieldDescriptor&, LinkInfo const&, Bytecodes::Code, bool, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/interpreter/linkResolver.cpp:1082:18
    #9 0x7f837f4ade9e in LinkResolver::resolve_field_access(fieldDescriptor&, constantPoolHandle const&, int, methodHandle const&, Bytecodes::Code, bool, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/interpreter/linkResolver.cpp:992:3
    #10 0x7f837e8bc361 in InterpreterRuntime::resolve_get_put(Bytecodes::Code, int, methodHandle&, constantPoolHandle&, bool, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/interpreter/interpreterRuntime.cpp:663:5
    #11 0x7f837e8bc077 in InterpreterRuntime::resolve_get_put(JavaThread*, Bytecodes::Code) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/interpreter/interpreterRuntime.cpp:649:3
    #12 0x7f837e8c73c2 in InterpreterRuntime::resolve_from_cache(JavaThread*, Bytecodes::Code) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/interpreter/interpreterRuntime.cpp:994:5
    #13 0x7f836f4a57f0  (<unknown module>)
    #14 0x7f836f487d00  (<unknown module>)
    #15 0x7f837e91689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #16 0x7f837e9127b8 in JavaCalls::call(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:324:3
    #17 0x7f837e9127b8 in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:251:3
    #18 0x7f837e912cda in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:257:3
    #19 0x7f8380cab6cb in call_initPhase1(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:298:3
    #20 0x7f8380ca8a6d in Threads::initialize_java_lang_classes(JavaThread*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:382:3
    #21 0x7f8380cad310 in Threads::create_vm(JavaVMInitArgs*, bool*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:669:3
    #22 0x7f837ecc135e in JNI_CreateJavaVM_inner(JavaVM_**, void**, void*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3589:12
    #23 0x7f837ecc135e in JNI_CreateJavaVM /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3680:14
    #24 0x7f83871e39d1 in InitializeJVM /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:1495:9
    #25 0x7f83871e39d1 in JavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:494:10
    #26 0x7f83871f0910 in ThreadJavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/unix/native/libjli/java_md.c:649:29
    #27 0x7f8386736a0a  (/home/yansendao/software/acc/x86_64/lib64/clang/17/lib/linux/libclang_rt.asan-x86_64.so+0x136a0a)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/unix/native/libjava/FileDescriptor_md.c:52:5 in
```
[configure-command.txt](https://github.com/user-attachments/files/18244489/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18244490/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18244491/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18244492/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18244493/make-linux-x86_64-server-fastdebug-1.log.zip)

**Comment by sendaoYan** [comment]
```
src/java.base/share/native/libjava/FileOutputStream.c:48:14: runtime error: call to function jni_GetFieldID through pointer to incorrect function type 'struct _jfieldID *(*)(const struct JNINativeInterface_ **, struct _jobject *, const char *, const char *)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:1747: note: jni_GetFieldID defined here
    #0 0x7f678db80783 in Java_java_io_FileOutputStream_initIDs /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/FileOutputStream.c:48:14
    #1 0x7f6779695d44  (<unknown module>)
    #2 0x7f677968f415  (<unknown module>)
    #3 0x7f6779687d00  (<unknown module>)
    #4 0x7f6788b1689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #5 0x7f6788a04c18 in InstanceKlass::call_class_initializer(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:1704:5
    #6 0x7f67889fb02a in InstanceKlass::initialize_impl(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:1313:7
    #7 0x7f67889f8777 in InstanceKlass::initialize(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:816:5
    #8 0x7f67889f9f44 in InstanceKlass::initialize_impl(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:1274:20
    #9 0x7f67889f8777 in InstanceKlass::initialize(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/oops/instanceKlass.cpp:816:5
    #10 0x7f6788aacf80 in InterpreterRuntime::_new(JavaThread*, ConstantPool*, int) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/interpreter/interpreterRuntime.cpp:221:10
    #11 0x7f67796a9c7b  (<unknown module>)
    #12 0x7f6779687d00  (<unknown module>)
    #13 0x7f6788b1689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #14 0x7f6788b127b8 in JavaCalls::call(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:324:3
    #15 0x7f6788b127b8 in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:251:3
    #16 0x7f6788b12cda in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:257:3
    #17 0x7f678aeab6cb in call_initPhase1(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:298:3
    #18 0x7f678aea8a6d in Threads::initialize_java_lang_classes(JavaThread*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:382:3
    #19 0x7f678aead310 in Threads::create_vm(JavaVMInitArgs*, bool*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:669:3
    #20 0x7f6788ec135e in JNI_CreateJavaVM_inner(JavaVM_**, void**, void*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3589:12
    #21 0x7f6788ec135e in JNI_CreateJavaVM /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3680:14
    #22 0x7f67914479d1 in InitializeJVM /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:1495:9
    #23 0x7f67914479d1 in JavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:494:10
    #24 0x7f6791454910 in ThreadJavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/unix/native/libjli/java_md.c:649:29
    #25 0x7f6790936a0a  (/home/yansendao/software/acc/x86_64/lib64/clang/17/lib/linux/libclang_rt.asan-x86_64.so+0x136a0a)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/FileOutputStream.c:48:14 in
```
[configure-command.txt](https://github.com/user-attachments/files/18245141/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18245142/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18245143/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18245144/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18245145/make-linux-x86_64-server-fastdebug-1.log.zip)
