### ISSUE TITLE
[ASAN][upstream][25][clang]System.c:266:9: runtime error: call to function jni_GetStaticFieldID through pointer to incorrect function type 'struct _jfieldID *(*)(const struct JNINativeInterface_ **, struct _jobject *, const char *, const char *)'

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#155]
Configure command:
```
export PATH=~/software/acc/`arch`/bin:$PATH ; export LD_LIBRARY_PATH=~/software/acc/`arch`/lib64/clang/17/lib/linux:$LD_LIBRARY_PATH ; export CFLAGS="-shared-libasan" ; export CXXFLAGS=$CFLAGS ; export LDFLAGS=$CFLAGS ; export "CUSTOM_CONFIG=--enable-asan --enable-ubsan --enable-lsan --with-toolchain-type=clang --with-toolchain-path=~/software/acc/`arch`/bin" && export ASAN_OPTIONS="detect_leaks=0,abort_on_error=0,verbosity=3" && export LSAN_OPTIONS=suppressions=$HOME/tone/tone-matrix-compiler/jtreg/asan/leak-suppressions.txt && export UBSAN_OPTIONS="suppressions=$HOME/tone/tone-matrix-compiler/jtreg/asan/suppressions-UndefinedBehavior-clang.txt,print_stacktrace=1"
bash configure --with-jobs=128 --prefix=/home/yansendao/git/jdk-asan-clang/install-fastdebug --verbose --with-debug-level=fastdebug --enable-unlimited-crypto --with-vendor-name=yansendao --with-vendor-url=https://github.com/sendaoYan --with-vendor-bug-url=mailto:yansendao.ysd@alibaba-inc.com --with-vendor-vm-bug-url=mailto:yansendao.ysd@alibaba-inc.com --with-jvm-variants=server --with-boot-jdk=/home/yansendao/software/jdk/24/jdk-repo-binary --with-gtest=/home/yansendao/git/googletest-v1.14.x --with-jtreg=/home/yansendao/software/jdk/jtreg-7.4 --with-jmh=build/jmh/jars    --with-version-opt=23d6f747 --with-zlib=system --enable-ccache --with-native-debug-symbols=external --with-extra-cflags=-shared-libasan --with-extra-cxxflags=-shared-libasan --with-extra-ldflags=-shared-libasan  --enable-asan --enable-ubsan --enable-lsan --with-toolchain-type=clang --with-toolchain-path=~/software/acc/x86_64/bin
```

Standalone command:
```shell
/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/jdk/bin/javac -J-Djava.io.tmpdir=/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/support/javatmp -g -Xlint:all -source 25 -target 25 -implicit:none -Xprefer:source -XDignore.symbol.file=true -encoding ascii -Werror --add-modules jdk.compiler,jdk.jdeps --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.jvm=ALL-UNNAMED --add-exports jdk.jdeps/com.sun.tools.classfile=ALL-UNNAMED -Xlint:-options -XDmodifiedInputs=/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.modfiles.fixed -d /home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac @/home/yansendao/git/jdk-asan-clang/build/linux-x86_64-server-fastdebug/buildtools/create_symbols_javac/_the.COMPILE_CREATE_SYMBOLS_batch.filelist
```

result:
```
src/java.base/share/native/libjava/System.c:266:9: runtime error: call to function jni_GetStaticFieldID through pointer to incorrect function type 'struct _jfieldID *(*)(const struct JNINativeInterface_ **, struct _jobject *, const char *, const char *)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:1974: note: jni_GetStaticFieldID defined here
    #0 0x7effd875b161 in Java_java_lang_System_setIn0 /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/System.c:266:9
    #1 0x7effc4295d44  (<unknown module>)
    #2 0x7effc428f415  (<unknown module>)
    #3 0x7effc4287d00  (<unknown module>)
    #4 0x7effd371689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #5 0x7effd37127b8 in JavaCalls::call(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:324:3
    #6 0x7effd37127b8 in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:251:3
    #7 0x7effd3712cda in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:257:3
    #8 0x7effd5aab6cb in call_initPhase1(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:298:3
    #9 0x7effd5aa8a6d in Threads::initialize_java_lang_classes(JavaThread*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:382:3
    #10 0x7effd5aad310 in Threads::create_vm(JavaVMInitArgs*, bool*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:669:3
    #11 0x7effd3ac135e in JNI_CreateJavaVM_inner(JavaVM_**, void**, void*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3589:12
    #12 0x7effd3ac135e in JNI_CreateJavaVM /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3680:14
    #13 0x7effdc0219d1 in InitializeJVM /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:1495:9
    #14 0x7effdc0219d1 in JavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:494:10
    #15 0x7effdc02e910 in ThreadJavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/unix/native/libjli/java_md.c:649:29
    #16 0x7effdb536a0a  (/home/yansendao/software/acc/x86_64/lib64/clang/17/lib/linux/libclang_rt.asan-x86_64.so+0x136a0a)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/System.c:266:9 in
```

[configure-command.txt](https://github.com/user-attachments/files/18245153/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18245154/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18245156/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18245157/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18245158/make-linux-x86_64-server-fastdebug-1.log.zip)

**Comment by sendaoYan** [comment]
```
src/java.base/share/native/libjava/System.c:276:9: runtime error: call to function jni_GetStaticFieldID through pointer to incorrect function type 'struct _jfieldID *(*)(const struct JNINativeInterface_ **, struct _jobject *, const char *, const char *)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:1974: note: jni_GetStaticFieldID defined here
    #0 0x7f52c9dc6311 in Java_java_lang_System_setOut0 /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/System.c:276:9
    #1 0x7f52b5895d44  (<unknown module>)
    #2 0x7f52b588f415  (<unknown module>)
    #3 0x7f52b5887d00  (<unknown module>)
    #4 0x7f52c4d1689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #5 0x7f52c4d127b8 in JavaCalls::call(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:324:3
    #6 0x7f52c4d127b8 in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:251:3
    #7 0x7f52c4d12cda in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:257:3
    #8 0x7f52c70ab6cb in call_initPhase1(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:298:3
    #9 0x7f52c70a8a6d in Threads::initialize_java_lang_classes(JavaThread*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:382:3
    #10 0x7f52c70ad310 in Threads::create_vm(JavaVMInitArgs*, bool*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:669:3
    #11 0x7f52c50c135e in JNI_CreateJavaVM_inner(JavaVM_**, void**, void*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3589:12
    #12 0x7f52c50c135e in JNI_CreateJavaVM /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3680:14
    #13 0x7f52cd6b79d1 in InitializeJVM /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:1495:9
    #14 0x7f52cd6b79d1 in JavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:494:10
    #15 0x7f52cd6c4910 in ThreadJavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/unix/native/libjli/java_md.c:649:29
    #16 0x7f52ccb36a0a  (/home/yansendao/software/acc/x86_64/lib64/clang/17/lib/linux/libclang_rt.asan-x86_64.so+0x136a0a)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/System.c:276:9 in
```
[configure-command.txt](https://github.com/user-attachments/files/18245167/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18245168/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18245169/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18245170/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18245171/make-linux-x86_64-server-fastdebug-1.log.zip)

**Comment by sendaoYan** [comment]
```
src/java.base/share/native/libjava/System.c:286:9: runtime error: call to function jni_GetStaticFieldID through pointer to incorrect function type 'struct _jfieldID *(*)(const struct JNINativeInterface_ **, struct _jobject *, const char *, const char *)'
/home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:1974: note: jni_GetStaticFieldID defined here
    #0 0x7f9aa8bc64c1 in Java_java_lang_System_setErr0 /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjava/System.c:286:9
    #1 0x7f9a94695d44  (<unknown module>)
    #2 0x7f9a9468f415  (<unknown module>)
    #3 0x7f9a94687d00  (<unknown module>)
    #4 0x7f9aa3b1689d in JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:416:7
    #5 0x7f9aa3b127b8 in JavaCalls::call(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:324:3
    #6 0x7f9aa3b127b8 in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:251:3
    #7 0x7f9aa3b12cda in JavaCalls::call_static(JavaValue*, Klass*, Symbol*, Symbol*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/javaCalls.cpp:257:3
    #8 0x7f9aa5eab6cb in call_initPhase1(JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:298:3
    #9 0x7f9aa5ea8a6d in Threads::initialize_java_lang_classes(JavaThread*, JavaThread*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:382:3
    #10 0x7f9aa5ead310 in Threads::create_vm(JavaVMInitArgs*, bool*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/runtime/threads.cpp:669:3
    #11 0x7f9aa3ec135e in JNI_CreateJavaVM_inner(JavaVM_**, void**, void*) /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3589:12
    #12 0x7f9aa3ec135e in JNI_CreateJavaVM /home/yansendao/git/jdk-asan-clang/src/hotspot/share/prims/jni.cpp:3680:14
    #13 0x7f9aac4e49d1 in InitializeJVM /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:1495:9
    #14 0x7f9aac4e49d1 in JavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/share/native/libjli/java.c:494:10
    #15 0x7f9aac4f1910 in ThreadJavaMain /home/yansendao/git/jdk-asan-clang/src/java.base/unix/native/libjli/java_md.c:649:29
    #16 0x7f9aab936a0a  (/home/yansendao/software/acc/x86_64/lib64/clang/17/lib/linux/libclang_rt.asan-x86_64.so+0x136a0a)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/java.base/share/native/libjava/System.c:286:9 in
```
[configure-command.txt](https://github.com/user-attachments/files/18245176/configure-command.txt)
[configure-linux-x86_64-server-fastdebug.log](https://github.com/user-attachments/files/18245177/configure-linux-x86_64-server-fastdebug.log)
[make-linux-x86_64-server-fastdebug-2.log](https://github.com/user-attachments/files/18245178/make-linux-x86_64-server-fastdebug-2.log)
[buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log](https://github.com/user-attachments/files/18245180/buildtools_create_symbols_javac__the.COMPILE_CREATE_SYMBOLS_batch.cmdline.log)
[make-linux-x86_64-server-fastdebug-1.log.zip](https://github.com/user-attachments/files/18245181/make-linux-x86_64-server-fastdebug-1.log.zip)
