### ISSUE TITLE
[jdk23]vmTestbase/nsk/jvmti/scenarios/events/EM07/em07t002/TestDescription.java intermittently fail: -XX:-UseGCOverheadLimit, nsk.jvmti.scenarios.events.EM07.em07t002, ./bin/loadclass] exit code is 137

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#17]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/273509

```
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.AssertionError: [/var/tmp/tone/run/jtreg/binary-download/jdk-11.0.20.20+0/bin/java, -Djdk.lang.processReaperUseDefaultStackSize=true, -Dtest.wisp.socketAddress=www.alibabacloud.com, -Xmixed, -XX:+UseVtableBasedCHA, -XX:+LightWeightBarrier, -XX:+UseCompactObjectHeaders, -ea, -esa, -cp, /var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/vmTestbase/nsk/jvmti/scenarios/events/EM07/em07t002/TestDescription.d:/var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/vmTestbase:/var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/test/lib, -Djava.library.path=/var/tmp/tone/run/jtreg/test-images/jdk-11.0.20.20+0-test-image/hotspot/jtreg/native, -agentlib:em07t002=attempts=2 -waittime=5, -XX:-UseGCOverheadLimit, nsk.jvmti.scenarios.events.EM07.em07t002, ./bin/loadclass] exit code is 137
REASON: User specified action: run main/othervm/native PropertyResolvingWrapper ExecDriver --java "-agentlib:em07t002=attempts=2 -waittime=5" -XX:-UseGCOverheadLimit nsk.jvmti.scenarios.events.EM07.em07t002 ./bin/loadclass 
TIME:   14.979 seconds
messages:
command: main PropertyResolvingWrapper ExecDriver --java "-agentlib:em07t002=attempts=2 -waittime=5" -XX:-UseGCOverheadLimit nsk.jvmti.scenarios.events.EM07.em07t002 ./bin/loadclass
reason: User specified action: run main/othervm/native PropertyResolvingWrapper ExecDriver --java "-agentlib:em07t002=attempts=2 -waittime=5" -XX:-UseGCOverheadLimit nsk.jvmti.scenarios.events.EM07.em07t002 ./bin/loadclass 
Mode: othervm [/othervm specified]
elapsed time (seconds): 14.979
configuration:
STDOUT:
run [ExecDriver, --java, -agentlib:em07t002=attempts=2 -waittime=5, -XX:-UseGCOverheadLimit, nsk.jvmti.scenarios.events.EM07.em07t002, ./bin/loadclass]
exec [/var/tmp/tone/run/jtreg/binary-download/jdk-11.0.20.20+0/bin/java, -Djdk.lang.processReaperUseDefaultStackSize=true, -Dtest.wisp.socketAddress=www.alibabacloud.com, -Xmixed, -XX:+UseVtableBasedCHA, -XX:+LightWeightBarrier, -XX:+UseCompactObjectHeaders, -ea, -esa, -cp, /var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/vmTestbase/nsk/jvmti/scenarios/events/EM07/em07t002/TestDescription.d:/var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/vmTestbase:/var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/test/lib, -Djava.library.path=/var/tmp/tone/run/jtreg/test-images/jdk-11.0.20.20+0-test-image/hotspot/jtreg/native, -agentlib:em07t002=attempts=2 -waittime=5, -XX:-UseGCOverheadLimit, nsk.jvmti.scenarios.events.EM07.em07t002, ./bin/loadclass]
STDERR:
java.lang.AssertionError: [/var/tmp/tone/run/jtreg/binary-download/jdk-11.0.20.20+0/bin/java, -Djdk.lang.processReaperUseDefaultStackSize=true, -Dtest.wisp.socketAddress=www.alibabacloud.com, -Xmixed, -XX:+UseVtableBasedCHA, -XX:+LightWeightBarrier, -XX:+UseCompactObjectHeaders, -ea, -esa, -cp, /var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/vmTestbase/nsk/jvmti/scenarios/events/EM07/em07t002/TestDescription.d:/var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/vmTestbase:/var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/test/lib, -Djava.library.path=/var/tmp/tone/run/jtreg/test-images/jdk-11.0.20.20+0-test-image/hotspot/jtreg/native, -agentlib:em07t002=attempts=2 -waittime=5, -XX:-UseGCOverheadLimit, nsk.jvmti.scenarios.events.EM07.em07t002, ./bin/loadclass] exit code is 137
	at ExecDriver.main(ExecDriver.java:137)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at PropertyResolvingWrapper.main(PropertyResolvingWrapper.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:991)

JavaTest Message: Test threw exception: java.lang.AssertionError: [/var/tmp/tone/run/jtreg/binary-download/jdk-11.0.20.20+0/bin/java, -Djdk.lang.processReaperUseDefaultStackSize=true, -Dtest.wisp.socketAddress=www.alibabacloud.com, -Xmixed, -XX:+UseVtableBasedCHA, -XX:+LightWeightBarrier, -XX:+UseCompactObjectHeaders, -ea, -esa, -cp, /var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/vmTestbase/nsk/jvmti/scenarios/events/EM07/em07t002/TestDescription.d:/var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/vmTestbase:/var/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/12/test/lib, -Djava.library.path=/var/tmp/tone/run/jtreg/test-images/jdk-11.0.20.20+0-test-image/hotspot/jtreg/native, -agentlib:em07t002=attempts=2 -waittime=5, -XX:-UseGCOverheadLimit, nsk.jvmti.scenarios.events.EM07.em07t002, ./bin/loadclass] exit code is 137
JavaTest Message: shutting down test
```

**Comment by sendaoYan** [comment]
rerun job: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/274092

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/15562842
