### ISSUE TITLE
[jdk23]java/net/ipv6tests/UdpTest.java timeout

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#18]
bug记录：https://bugs.java.com/bugdatabase/view_bug?bug_id=8198266

上午6点的job是pass的：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/275183
中午12点的job是fail的：https://tone.aliyun-inc.com/ws/xesljfzh/test_result/275232

```

"MainThread" #31 [151765] prio=5 os_prio=0 cpu=41.94ms elapsed=480.17s tid=0x0000ffff8c1a6200 nid=151765 runnable  [0x0000ffff51602000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.DatagramChannelImpl.receive0(java.base@23/Native Method)
	at sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(java.base@23/DatagramChannelImpl.java:814)
	at sun.nio.ch.DatagramChannelImpl.receive(java.base@23/DatagramChannelImpl.java:790)
	at sun.nio.ch.DatagramChannelImpl.tryBlockingReceive(java.base@23/DatagramChannelImpl.java:751)
	at sun.nio.ch.DatagramChannelImpl.blockingReceive(java.base@23/DatagramChannelImpl.java:692)
	at sun.nio.ch.DatagramSocketAdaptor.receive(java.base@23/DatagramSocketAdaptor.java:204)
	at java.net.DatagramSocket.receive(java.base@23/DatagramSocket.java:718)
	at Tests.datagramEcho(Tests.java:134)
	at UdpTest.test1(UdpTest.java:128)
	at UdpTest.main(UdpTest.java:87)
	at java.lang.invoke.LambdaForm$DMH/0x0000780001004400.invokeStatic(java.base@23/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000780001005400.invoke(java.base@23/LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@23/Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@23/DirectMethodHandleAccessor.java:154)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@23/DirectMethodHandleAccessor.java:103)
	at java.lang.reflect.Method.invoke(java.base@23/Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.lang.Thread.runWith(java.base@23/Thread.java:1588)
	at java.lang.Thread.run(java.base@23/Thread.java:1575)

"Attach Listener" #32 [151800] daemon prio=9 os_prio=0 cpu=0.17ms elapsed=0.10s tid=0x0000ffff1c000ec0 nid=151800 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=1.61ms elapsed=480.19s tid=0x0000ffff8c14d560 nid=151753 runnable  

"GC Thread#0" os_prio=0 cpu=0.08ms elapsed=480.20s tid=0x0000ffff8c0531c0 nid=151747 runnable  

"G1 Main Marker" os_prio=0 cpu=0.05ms elapsed=480.20s tid=0x0000ffff8c063bd0 nid=151748 runnable  

"G1 Conc#0" os_prio=0 cpu=0.07ms elapsed=480.20s tid=0x0000ffff8c064bc0 nid=151749 runnable  

"G1 Refine#0" os_prio=0 cpu=0.07ms elapsed=480.20s tid=0x0000ffff8c117bf0 nid=151750 runnable  

"G1 Service" os_prio=0 cpu=3.14ms elapsed=480.20s tid=0x0000ffff8c118bc0 nid=151751 runnable  

"VM Periodic Task Thread" os_prio=0 cpu=34.67ms elapsed=480.19s tid=0x0000ffff8c1314e0 nid=151752 waiting on condition  

JNI global refs: 27, weak refs: 0

--- Timeout information end.
finished: Tue Jan 30 16:19:04 CST 2024
elapsed time (seconds): 480.23
configuration:
STDOUT:
Local Addresses
/172.17.0.1
/fe80:0:0:0:dca6:76ff:fe76:2824%vethf59a93c
Test1 starting
dest1 = /172.17.0.1:43209
dest2 = /172.17.0.1:58245
dest1 = /[fe80:0:0:0:dca6:76ff:fe76:2824%vethf59a93c]:44018
dest2 = /[fe80:0:0:0:dca6:76ff:fe76:2824%vethf59a93c]:45202
dest1 = /[fe80:0:0:0:dca6:76ff:fe76:2824%vethf59a93c]:43185
dest2 = /[fe80:0:0:0:dca6:76ff:fe76:2824%vethf59a93c]:45310
dest1 = /[fe80:0:0:0:dca6:76ff:fe76:2824%vethf59a93c]:53009
dest2 = /172.17.0.1:60247
dest2 = /[fe80:0:0:0:dca6:76ff:fe76:2824%vethf59a93c]:52912
dest2 = /172.17.0.1:52912
Timeout signalled after 480 seconds
```

加上-Djava.net.preferIPv4Stack=true选项用例pass：

![image](https://github.com/dragonwell-project/dragonwell21/assets/24123821/5a08df4b-a6b5-4f8a-be82-8ec890feef35)

**Comment by sendaoYan** [comment]
可能和https://bugs.openjdk.org/browse/JDK-8281511是同一个问题

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/20763824
