### ISSUE TITLE
[jdk]CAInterop.java#globalsigneccrootcar4 Failed to validate https://revoked.gsr4.demo.pki.goog

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#19]
job: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/275455
rerun job: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/275671

4 testcases Failed to validate

```
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#globalsigneccrootcar4 
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#gtsrootcar1 
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#gtsrootcar2 
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#gtsrootecccar3 
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#gtsrootecccar4 
```

```
% grep "^java.lang.RuntimeException: Failed to validate" jtreg.stdout.log      
java.lang.RuntimeException: Failed to validate https://revoked.gsr4.demo.pki.goog
java.lang.RuntimeException: Failed to validate https://revoked.gtsr2.demo.pki.goog
java.lang.RuntimeException: Failed to validate https://revoked.gtsr1.demo.pki.goog
java.lang.RuntimeException: Failed to validate https://revoked.gtsr3.demo.pki.goog
java.lang.RuntimeException: Failed to validate https://revoked.gtsr4.demo.pki.goog
```

```
% grep "^java.lang.RuntimeException: Failed to validate" jtreg.stdout.log -A3
java.lang.RuntimeException: Failed to validate https://revoked.gsr4.demo.pki.goog
        at ValidatePathWithURL.validateDomain(ValidatePathWithURL.java:129)
        at CAInterop.validate(CAInterop.java:692)
        at CAInterop.main(CAInterop.java:630)
--
java.lang.RuntimeException: Failed to validate https://revoked.gtsr2.demo.pki.goog
        at ValidatePathWithURL.validateDomain(ValidatePathWithURL.java:129)
        at CAInterop.validate(CAInterop.java:692)
        at CAInterop.main(CAInterop.java:630)
--
java.lang.RuntimeException: Failed to validate https://revoked.gtsr1.demo.pki.goog
        at ValidatePathWithURL.validateDomain(ValidatePathWithURL.java:129)
        at CAInterop.validate(CAInterop.java:692)
        at CAInterop.main(CAInterop.java:630)
--
java.lang.RuntimeException: Failed to validate https://revoked.gtsr3.demo.pki.goog
        at ValidatePathWithURL.validateDomain(ValidatePathWithURL.java:129)
        at CAInterop.validate(CAInterop.java:692)
        at CAInterop.main(CAInterop.java:630)
--
java.lang.RuntimeException: Failed to validate https://revoked.gtsr4.demo.pki.goog
        at ValidatePathWithURL.validateDomain(ValidatePathWithURL.java:129)
        at CAInterop.validate(CAInterop.java:692)
        at CAInterop.main(CAInterop.java:630)
```

**Comment by sendaoYan** [comment]
can not replay
