### ISSUE TITLE
[upstream][jdk23]compiler/c2/cr7200264/TestSSE2IntVect.java intermittently fail after JDK-8291809

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#22]
job: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/278011

test command:
```bash
export test=test/hotspot/jtreg/compiler/c2/cr7200264/TestIntVect.java
function runJtreg() { jtreg -ea -esa -timeoutFactor:4 -v:fail,error,time,nopass -nr -w $dir/index-$1 $test &> $dir/$1.log ; if [[ 0 -ne $? ]] ; then echo -n "$1 " ; else rm -rf $dir/index-$1 $dir/$1.log ; fi ; } ; export -f runJtreg ; export dir="tmp-jtreg-"`basename ${test##* } .java | sed "s|#|_|"` ; rm -rf $dir ; mkdir -p $dir ; time seq 100000 | xargs -i -n 1 -P `nproc` bash -c "runJtreg {}" ; echo total fail number: `ls $dir/*.log 2> /dev/null | wc | awk '{print $1}'`
```

result:
```
compiler.lib.ir_framework.driver.irmatching.IRViolationException: There were one or multiple IR rule failures. Please check stderr for more information.
	at compiler.lib.ir_framework.driver.irmatching.IRMatcher.reportFailures(IRMatcher.java:61)
	at compiler.lib.ir_framework.driver.irmatching.IRMatcher.match(IRMatcher.java:49)
	at compiler.lib.ir_framework.TestFramework.runTestVM(TestFramework.java:754)
	at compiler.lib.ir_framework.TestFramework.start(TestFramework.java:719)
	at compiler.lib.ir_framework.TestFramework.start(TestFramework.java:339)
	at compiler.lib.ir_framework.TestFramework.run(TestFramework.java:223)
	at compiler.lib.ir_framework.TestFramework.run(TestFramework.java:212)
	at compiler.c2.cr7200264.TestIntVect.main(TestIntVect.java:49)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1575)
```

[hotspot_pid174041.log](https://github.com/dragonwell-project/dragonwell21/files/14173885/hotspot_pid174041.log)
[pid-173989-output.log](https://github.com/dragonwell-project/dragonwell21/files/14173886/pid-173989-output.log)
[pid-174041-output.log](https://github.com/dragonwell-project/dragonwell21/files/14173887/pid-174041-output.log)
[test-vm-compile-commands-pid-173989.log](https://github.com/dragonwell-project/dragonwell21/files/14173888/test-vm-compile-commands-pid-173989.log)
[test-vm-flags-pid-173989.log](https://github.com/dragonwell-project/dragonwell21/files/14173889/test-vm-flags-pid-173989.log)
[TestIntVect.log](https://github.com/dragonwell-project/dragonwell21/files/14173890/TestIntVect.log)

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8325277

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/15678521
