### ISSUE TITLE
[upstream][23]Test RuntimeMXBean001.java intermittent fails

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell21#52]
job: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/314161

test commnad:
```shell
export test=test/hotspot/jtreg/vmTestbase/nsk/monitoring/RuntimeMXBean/RuntimeMXBean001/RuntimeMXBean001.java
function runJtreg() { jtreg -ea -esa -timeoutFactor:4 -v:fail,error,time,nopass -nr -w $dir/index-$1 $test &> $dir/$1.log ; if [[ 0 -ne $? ]] ; then echo -n "$1 " ; else rm-rf $dir/index-$1 $dir/$1.log ; fi ; } ; export -f runJtreg ; export dir="tmp-jtreg-"`basename ${test##* } .java | sed "s|#|_|"` ; rm -rf $dir ; mkdir -p $dir ; time seq 100000 | xargs -i -n 1 -P `nproc` bash -c "runJtreg {}" ; echo total fail number: `ls $dir/*.log 2> /dev/null | wc | awk '{print $1}'`
```

result:
```
Iteration: 0
startTime: 1716297435648, uptime1: 109, time1: 4595315
Iteration: 1
startTime: 1716297435648, uptime1: 4386, time1: 4599592
Iteration: 2
startTime: 1716297435648, uptime1: 8450, time1: 4603657
nsk.share.TestFailure: Difference between timeflow of uptime and current time is too big: 9640, expecting at most 5000
    at nsk.monitoring.RuntimeMXBean.RuntimeMXBean001.RuntimeMXBean001.testUptimeOne(RuntimeMXBean001.java:103)
    at nsk.monitoring.RuntimeMXBean.RuntimeMXBean001.RuntimeMXBean001.testUptime(RuntimeMXBean001.java:110)
    at nsk.monitoring.RuntimeMXBean.RuntimeMXBean001.RuntimeMXBean001.run(RuntimeMXBean001.java:115)
    at nsk.share.test.Tests$TestRunner.execute(Tests.java:82)
    at nsk.share.test.Tests$TestRunner.run(Tests.java:96)
    at nsk.monitoring.share.Monitoring.runTest(Monitoring.java:112)
```

[RuntimeMXBean001.java.log](https://github.com/dragonwell-project/dragonwell21/files/15397536/RuntimeMXBean001.java.log)

**Comment by sendaoYan** [comment]
rerun job: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/314449
